export { default as FuelGauge } from './FuelGauge'
export { default as FuelTemp } from './FuelTemp'
export { default as Revolutions } from './Revolutions'
export { default as Speedometer } from './Speedometer'
export { default as TempGauge } from './TempGauge'
export { default as Dashboard } from './Dashboard'